@startuml component
title Token-x-canary-dings Sequence Flow
skinparam maxMessageSize 300
autonumber

entity github as "Github"

box "NAIS Resources"
control digdirator as "Digdirator"
control jwker as "Jwker"
participant application as "Application"
participant tokendings as "Tokendings"
participant nais as "Secret"
participant prom as "Prometheus"
end box

box "External Resources"
participant slack as "Slack"
participant digdir as "Digdir"
end box

group Github
github -> application: trigger integration (10 min interval)
    group Fail | Cancelled
    github -> slack: POST message (3 min timeout)
    end
end

group Deployment
group Jwker
    jwker -> tokendings: Post client configuration
    jwker -> nais: update Jwk
end

group Digdirator (MaskinportenClient)
        digdirator -> nais: get currents private JWK(s)
        digdirator -> digdirator: rotate private JWK(s)
        digdirator -> digdir: update public JWKS set
        digdirator -> nais: inject private JWK and metadata
    end
end

nais -> application: mount secret and metadata

==Maskinporten Usage==
group Application
    group Unhealthy
        application -> application: pod restarts
        nais -> prom: alerts
    end
    application -> application: start create and sign JWT
    application -> digdir: request token with signed JWT
    digdir -> application: access_token
end

==TokenDings Usage==
group Application
    group Unhealthy
        application -> application: pod restarts
        nais -> prom: alerts
    end
    application -> application: start create and sign JWT
    application -> tokendings: request token with signed JWT and subject_token
    tokendings -> application: access_token
end

@enduml
