name: Deploy Cron Job

on:
  schedule:
    - cron: '*/10 * * * *'
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/digdirator-maskinporten:${{ github.sha }}

jobs:
  deploy-dev-gcp:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Deploy
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/gcp/naiserator-gcp.yml
          VARS: .nais/gcp/dev-gcp-vars.yml
      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_USERNAME: Digdirator Integration Test
          SLACK_COLOR: '#FF0000'
          SLACK_MESSAGE: ':scream: Check Cron Job Deployer'
          SLACK_TITLE: Deployment faild
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
